name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            README.md
            CLAUDE.md
            IMPLEMENTATION.md
            workbench-config.example.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create distribution archive
        run: |
          mkdir -p release
          cp -r dist package.json package-lock.json README.md release/
          tar -czf mcp-workbench-${{ github.ref_name }}.tar.gz -C release .

      - name: Upload distribution archive
        uses: softprops/action-gh-release@v1
        with:
          files: mcp-workbench-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
